# NumPy 
NumPy is a Python library.

NumPy is used for working with arrays.

NumPy is short for "Numerical Python.

## Why Use NumPy?

In Python we have lists that serve the purpose of arrays, but they are slow to process.

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

Arrays are very frequently used in data science, where speed and resources are very important.

## Why is NumPy Faster Than Lists?
NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

This behavior is called locality of reference in computer science.

This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.

### Which Language is NumPy written in?
NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in C or C++.

## Installation of NumPy
If you have Python and PIP already installed on a system, then installation of NumPy is very easy.

Install it using this command:

C:\Users\Your Name> pip install numpy
If this command fails, then use a python distribution that already has NumPy installed like, Anaconda, Spyder etc.

## Import NumPy
Once NumPy is installed, import it in your applications by adding the import keyword:

### Import numpy
Now NumPy is imported and ready to use.

In [1]:
import numpy

Now Numpy is imported and ready to use

In [5]:
import numpy
arr = numpy.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


You can see the above output is a shape of Array not List

### NumPy as np
NumPy is usually imported under the np alias.

### alias: 
In Python alias are an alternate name for referring to the same thing.

Create an alias with the as keyword while importing:

In [4]:
import numpy as np
arr = np.array([6,7,8,9,10])
print(arr)

[ 6  7  8  9 10]


### Create a NumPy ndarray Object
NumPy is used to work with arrays. The array object in NumPy is called ndarray.

We can create a NumPy ndarray object by using the array() function.

In [8]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
<class 'numpy.ndarray'>


### To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:

### Example
Use a tuple to create a NumPy array:

In [12]:
arr = np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]
<class 'numpy.ndarray'>


## let's have a look at 0-D , 1-D , 2-D , 3-D and n-D Arrays
### 0-D


In [13]:
arr = np.array(57)
print(arr)
print(arr.shape)

57
()


### 1-D

In [6]:
arr = np.array([1,2,3,4,5])
print(arr)
print(arr.shape)

[1 2 3 4 5]
(5,)


### 2-D

In [16]:
arr = np.array([[1,2,3,4,5],[5,4,3,2,1]])
print(arr)
print(arr.shape)

[[1 2 3 4 5]
 [5 4 3 2 1]]
(2, 5)


### 3-D

In [7]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print(arr.shape)
print(arr.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
2


### n-D Array

In [83]:
arr = np.array([5,6,7],ndmin=10)
print(arr)
print(arr.shape)
print(arr.ndim," Dimensions Array")

[[[[[[[[[[5 6 7]]]]]]]]]]
(1, 1, 1, 1, 1, 1, 1, 1, 1, 3)
10  Dimensions Array


in the above code output i.e : (1, 1, 1, 1, 1, 1, 1, 1, 1, 3)  there are nine 1's which refers to 9-D arrays of empty yet and the last elemeent which is 3 refers to the last array i.e: 10th array , so its a 10-D array

## NumPy Array Indexing

### Access Array Elements
Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.

The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [26]:
arr = np.array([1,2,3])
print("Element at first index ",arr[0])
print("Element at third index ",arr[2])

Element at first index  1
Element at third index  3


#### Access and Add any two index values

In [28]:
arr = np.array([7,8,9])
print("Sum of index 1 and 2 values is :",arr[1] + arr[2])

Sum of index 1 and 2 values is : 17


#### Access 2-D array by index
Access third element of second array

In [29]:
arr = np.array([[3,4,5],[5,4,3]])
print(arr[1,2])

3


#### Acces 3-D array by index
Access the third element of the second array of the first array

In [34]:
arr = np.array([[[11,22,33],[44,55,66],[77,88,99]]])
print(arr)
print(arr.ndim)
print(arr[0,1,2])

[[[11 22 33]
  [44 55 66]
  [77 88 99]]]
3
66


#### 3-D array of 2-D arrays

In [38]:
arr = np.array([[[11,22,33],[44,55,66]],[[77,88,99],[5,7,57]]])
print(arr)
print(arr.ndim)


[[[11 22 33]
  [44 55 66]]

 [[77 88 99]
  [ 5  7 57]]]
3


#### Access second element of the third array of first 

In [40]:
print(arr[0,1,1])

55


arr[0, 1, 1] prints the value 55.

And this is why:

The first number represents the first dimension, which contains two arrays:
[[11, 22, 33], [44, 55, 66]]
and:
[[77, 88, 99], [5, 7, 57]]

Since we selected 0, we are left with the first array:
[[11, 22, 33], [44, 55, 66]]

The second number represents the second dimension, which also contains two arrays:
[11, 22, 33]
and:
[44, 55, 66]
Since we selected 1, we are left with the second array:
[44, 55, 66]

The third number represents the third dimension, which contains three values:
44
55
66
Since we selected 1, we end up with the second value:
55

In [1]:
import  numpy as np
arr  = np.array([1,2,3])
print(arr)

[1 2 3]


In [3]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.ndim)
print(arr.shape)

[[1 2 3]
 [4 5 6]]
2
(2, 3)


In [ ]:
arr = np.array([[[1],[2],[3]]])
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr[0,2,0])

3


# Linear Algebra 

### np.dot: Computes the dot product of two arrays.

In [8]:
A = np.array([1,2,3,4,5])
B = np.array([6,7,8,9,10])
C = np.dot(A,B)
print(C)

130


### np.matmul: Performs matrix multiplication

In [24]:
A = np.array([[[1,2,3],[1,2,3]],[[4,5,6],[4,5,6]]])
B = np.array([[[22,56],[78,1],[11,12]],[[9,44],[67,57],[0,4]]])
# print(A.shape)
# print(B.shape)
# print(B.ndim)
print(np.matmul(A,B))

[[[211  94]
  [211  94]]

 [[371 485]
  [371 485]]]


### np.transpose: Transposes an array (flips rows and columns).

In [31]:
matA = np.array([[82,1,45,6],[4,66,123,777]])
matB = np.array([[99,33,678,4],[0,0,0,0]])
print("Original matrix \n",matA)
print("Transpose \n",matA.T)
print("Original matix \n",matB)
print("Transpose \n",matB.T)

Original matrix 
 [[ 82   1  45   6]
 [  4  66 123 777]]
Transpose 
 [[ 82   4]
 [  1  66]
 [ 45 123]
 [  6 777]]
Original matix 
 [[ 99  33 678   4]
 [  0   0   0   0]]
Transpose 
 [[ 99   0]
 [ 33   0]
 [678   0]
 [  4   0]]


### np.outer: Computes the outer product of two vectors

In [45]:
X = np.array([1,2,3])
Y = np.array([2,3,1])
for i in X:
    print(i," * ",Y)
print(np.outer(X,Y))

1  *  [2 3 1]
2  *  [2 3 1]
3  *  [2 3 1]
[[2 3 1]
 [4 6 2]
 [6 9 3]]


### np.cross: Computes the cross product of two vectors.

In [49]:
X = np.array([[1,2,3],[444,1,473],[0,100,99]])
Y = np.array([2,3,1])
print(np.cross(X,Y))

[[   -7     5    -1]
 [-1418   502  1330]
 [ -197   198  -200]]


### np.vdot: Computes the dot product of two vectors.
### point : if matrix A has ith elemets then matrix B should have ith elements regardless of order and shape 

In [59]:
P = np.array([221393,221397,221399,1418,0,700,1,2,99])
Q = np.array([[1,2,3],[444,1,473],[0,100,99]])
print(np.vdot(P,Q))

2299077


### np.inner: Computes the inner product of two arrays.
### matrices must have equal  number of elements

In [64]:
A3D =np.array([[[82,2]]])
B3D =np.array([[[1,3],[2,3]]])
print(np.inner(A3D,B3D))

[[[[ 88 170]]]]


### Determinant

In [75]:
A = np.array([[1,2],[3,44]])
A_Det = np.linalg.det(A)
print(A_Det)
print(type(A_Det))
print(np.round(A_Det))

37.99999999999999
<class 'numpy.float64'>
38.0


### Inverse

In [94]:
Inv = np.array([[1,2],[3,4]])
print(np.linalg.inv(Inv))
print(Inv)
print(Inv.ndim)

[[-2.   1. ]
 [ 1.5 -0.5]]
[[1 2]
 [3 4]]
2


### Eigenvalues and Eigenvectors
point :matrix order must be same

In [100]:
arr = np.array([[123,456],
                [84,57]])
eigenvalues , eigenvectors = np.linalg.eig(arr)
print(eigenvalues)
print(eigenvectors)

[ 288.47669888 -108.47669888]
[[ 0.9400193  -0.89169123]
 [ 0.34112125  0.45264417]]
